"""empty message

Revision ID: 03d942d156f4
Revises: 78e6af714d6a
Create Date: 2017-10-11 21:56:25.774699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d942d156f4'
down_revision = '78e6af714d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'consignor_images', 'consignors', ['consignor_id'], ['id'])
    op.create_foreign_key(None, 'couponsion', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'driver_self_orders', 'goods', ['goods_id'], ['id'])
    op.create_foreign_key(None, 'driver_self_orders', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'positions', 'users', ['user_id'], ['id'])
    op.add_column('tixianchengqings', sa.Column('caozuoyuan_id', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'tixianchengqings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tixianchengqings', type_='foreignkey')
    op.drop_column('tixianchengqings', 'caozuoyuan_id')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint(None, 'driver_self_orders', type_='foreignkey')
    op.drop_constraint(None, 'driver_self_orders', type_='foreignkey')
    op.drop_constraint(None, 'couponsion', type_='foreignkey')
    op.drop_constraint(None, 'consignor_images', type_='foreignkey')
    # ### end Alembic commands ###
