"""empty message

Revision ID: 118832293412
Revises: c5ac42d66ce3
Create Date: 2017-06-14 10:30:54.319509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '118832293412'
down_revision = 'c5ac42d66ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'drivers_ibfk_1', 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'users_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('users_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'drivers_ibfk_1', 'drivers', 'users', ['users_id'], ['id'])
    # ### end Alembic commands ###
