"""empty message

Revision ID: 164d37ae7ab4
Revises: 3a77194029ce
Create Date: 2017-07-21 11:04:25.156419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164d37ae7ab4'
down_revision = '3a77194029ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_pays', sa.Column('drivers_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_pays', 'drivers', ['drivers_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_pays', type_='foreignkey')
    op.drop_column('order_pays', 'drivers_id')
    # ### end Alembic commands ###
