"""empty message

Revision ID: 17b1e1fcb235
Revises: 8ca950096c62
Create Date: 2017-07-25 16:42:30.053635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17b1e1fcb235'
down_revision = '8ca950096c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Driver_self_orders', sa.Column('driver', sa.Integer(), nullable=True))
    op.drop_constraint(u'driver_self_orders_ibfk_2', 'Driver_self_orders', type_='foreignkey')
    op.create_foreign_key(None, 'Driver_self_orders', 'drivers', ['driver'], ['id'])
    op.drop_column('Driver_self_orders', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Driver_self_orders', sa.Column('user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Driver_self_orders', type_='foreignkey')
    op.create_foreign_key(u'driver_self_orders_ibfk_2', 'Driver_self_orders', 'users', ['user'], ['id'])
    op.drop_column('Driver_self_orders', 'driver')
    # ### end Alembic commands ###
