"""empty message

Revision ID: 1e9370d364a5
Revises: 5c4f671395c8
Create Date: 2017-06-14 09:04:07.817491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e9370d364a5'
down_revision = '5c4f671395c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('users_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'drivers_ibfk_1', 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'users', ['users_id'], ['id'])
    op.drop_column('drivers', 'users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('users', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key(u'drivers_ibfk_1', 'drivers', 'users', ['users'], ['id'])
    op.drop_column('drivers', 'users_id')
    # ### end Alembic commands ###
