"""empty message

Revision ID: 273ce7f52d3a
Revises: 0bd8cee5da01
Create Date: 2017-09-28 15:29:57.831239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273ce7f52d3a'
down_revision = '0bd8cee5da01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'consignor_images', 'consignors', ['consignor_id'], ['id'])
    op.create_foreign_key(None, 'couponsion', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'driver_self_orders', 'goods', ['goods_id'], ['id'])
    op.create_foreign_key(None, 'driver_self_orders', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'positions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tixianchengqings', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('is_location', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_location')
    op.drop_constraint(None, 'tixianchengqings', type_='foreignkey')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint(None, 'driver_self_orders', type_='foreignkey')
    op.drop_constraint(None, 'driver_self_orders', type_='foreignkey')
    op.drop_constraint(None, 'couponsion', type_='foreignkey')
    op.drop_constraint(None, 'consignor_images', type_='foreignkey')
    # ### end Alembic commands ###
