"""empty message

Revision ID: 2a7e1cbc3ce3
Revises: 
Create Date: 2017-06-14 08:51:29.605291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a7e1cbc3ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('drivers', sa.Column('users', sa.Integer(), nullable=True))
    op.drop_constraint(u'drivers_ibfk_1', 'drivers', type_='foreignkey')
    op.create_foreign_key(None, 'drivers', 'users', ['users'], ['id'])
    op.drop_column('drivers', 'brand')
    op.drop_column('drivers', 'master')
    op.drop_constraint(u'users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'driver_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('driver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_1', 'users', 'drivers', ['driver_id'], ['id'])
    op.add_column('drivers', sa.Column('master', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('drivers', sa.Column('brand', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.create_foreign_key(u'drivers_ibfk_1', 'drivers', 'users', ['master'], ['id'])
    op.drop_column('drivers', 'users')
    op.drop_column('drivers', 'note')
    # ### end Alembic commands ###
