"""empty message

Revision ID: 354a631846c7
Revises: 1e9370d364a5
Create Date: 2017-06-14 09:24:39.926857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354a631846c7'
down_revision = '1e9370d364a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'driver_id')
    # ### end Alembic commands ###
