"""empty message

Revision ID: 3a77194029ce
Revises: 1183da32987e
Create Date: 2017-07-21 10:13:00.424423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a77194029ce'
down_revision = '1183da32987e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('end_xiangxi_address', sa.String(length=255), nullable=True))
    op.add_column('goods', sa.Column('start_xiangxi_address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'start_xiangxi_address')
    op.drop_column('goods', 'end_xiangxi_address')
    # ### end Alembic commands ###
