"""empty message

Revision ID: 3d4cd63bf5a0
Revises: fd0d20578209
Create Date: 2017-07-29 10:54:21.274124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4cd63bf5a0'
down_revision = 'fd0d20578209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_posts', sa.Column('make_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_posts', 'make_count')
    # ### end Alembic commands ###
