"""empty message

Revision ID: 4cb86a5a71b7
Revises: 
Create Date: 2017-06-13 11:49:45.466587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb86a5a71b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('length', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=255), nullable=True),
    sa.Column('frame_number', sa.String(length=255), nullable=True),
    sa.Column('engine_number', sa.String(length=255), nullable=True),
    sa.Column('driver_number', sa.String(length=255), nullable=True),
    sa.Column('break_number', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column(u'users', sa.Column('fleet_id', sa.Integer(), nullable=True))
    op.add_column(u'users', sa.Column('goods_owner_id', sa.Integer(), nullable=True))
    op.add_column(u'users', sa.Column('mail', sa.String(length=100), nullable=True))
    op.add_column(u'users', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column(u'users', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column(u'users', sa.Column('status', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_unique_constraint(None, 'users', ['mail'])
    op.create_foreign_key(None, 'users', 'driver', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column(u'users', 'status')
    op.drop_column(u'users', 'price')
    op.drop_column(u'users', 'phone')
    op.drop_column(u'users', 'mail')
    op.drop_column(u'users', 'goods_owner_id')
    op.drop_column(u'users', 'fleet_id')
    op.drop_column(u'users', 'driver_id')
    op.drop_table('driver_images')
    op.drop_table('driver')
    # ### end Alembic commands ###
