"""empty message

Revision ID: 5c4f671395c8
Revises: 2a7e1cbc3ce3
Create Date: 2017-06-14 08:53:22.916290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c4f671395c8'
down_revision = '2a7e1cbc3ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('driver', sa.String(length=255), nullable=True))
    op.add_column('drivers', sa.Column('travel', sa.String(length=255), nullable=True))
    op.drop_column('drivers', 'driver_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('driver_number', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('drivers', 'travel')
    op.drop_column('drivers', 'driver')
    # ### end Alembic commands ###
