"""empty message

Revision ID: 63701cc28bed
Revises: 86d138a014de
Create Date: 2017-06-14 11:46:57.175357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63701cc28bed'
down_revision = '86d138a014de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'drivers_ibfk_1', 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'master')
    op.add_column('users', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'driver_id')
    op.add_column('drivers', sa.Column('master', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'drivers_ibfk_1', 'drivers', 'users', ['master'], ['id'])
    # ### end Alembic commands ###
