"""empty message

Revision ID: 66d19cbe4885
Revises: 830a0f41849b
Create Date: 2017-07-21 09:02:19.862565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d19cbe4885'
down_revision = '830a0f41849b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(length=80), nullable=True),
    sa.Column('tiji', sa.String(length=80), nullable=True),
    sa.Column('zhongliang', sa.String(length=80), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_infos')
    # ### end Alembic commands ###
