"""empty message

Revision ID: 6a2ec451473d
Revises: 63701cc28bed
Create Date: 2017-06-14 11:48:06.822690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a2ec451473d'
down_revision = '63701cc28bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('master', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'users', ['master'], ['id'])
    op.drop_constraint(u'users_ibfk_3', 'users', type_='foreignkey')
    op.drop_column('users', 'driver_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('driver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_3', 'users', 'drivers', ['driver_id'], ['id'])
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'master')
    # ### end Alembic commands ###
