"""empty message

Revision ID: 78e6af714d6a
Revises: 273ce7f52d3a
Create Date: 2017-10-07 13:56:21.958314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e6af714d6a'
down_revision = '273ce7f52d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('func_id', sa.String(length=200), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('func', sa.String(length=100), nullable=True),
    sa.Column('args', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'consignor_images', 'consignors', ['consignor_id'], ['id'])
    op.create_foreign_key(None, 'couponsion', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'driver_self_orders', 'goods', ['goods_id'], ['id'])
    op.create_foreign_key(None, 'driver_self_orders', 'drivers', ['driver_id'], ['id'])
    op.create_foreign_key(None, 'positions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tixianchengqings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tixianchengqings', type_='foreignkey')
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint(None, 'driver_self_orders', type_='foreignkey')
    op.drop_constraint(None, 'driver_self_orders', type_='foreignkey')
    op.drop_constraint(None, 'couponsion', type_='foreignkey')
    op.drop_constraint(None, 'consignor_images', type_='foreignkey')
    op.drop_table('scheduler_tasks')
    # ### end Alembic commands ###
