"""empty message

Revision ID: 7fb0e45b8abe
Revises: a123566b47c5
Create Date: 2017-06-15 16:23:41.257367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb0e45b8abe'
down_revision = 'a123566b47c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_goods_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('start_address', sa.String(length=255), nullable=True),
    sa.Column('end_address', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('start_car_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('end_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('car_user_id', sa.Integer(), nullable=True),
    sa.Column('receive_time', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('goods_comments')
    # ### end Alembic commands ###
