"""empty message

Revision ID: 8ca950096c62
Revises: 5a9a25e9501f
Create Date: 2017-07-24 22:37:37.665928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca950096c62'
down_revision = '5a9a25e9501f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Driver_self_orders', sa.Column('static', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Driver_self_orders', 'static')
    # ### end Alembic commands ###
