"""empty message

Revision ID: a123566b47c5
Revises: 115205e2bfc2
Create Date: 2017-06-15 11:39:27.969629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a123566b47c5'
down_revision = '115205e2bfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignors', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('consignors', sa.Column('break_number', sa.Integer(), nullable=True))
    op.add_column('consignors', sa.Column('company_industry', sa.String(length=50), nullable=True))
    op.add_column('consignors', sa.Column('company_size', sa.String(length=50), nullable=True))
    op.add_column('consignors', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('consignors', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('consignors', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('consignors', sa.Column('state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consignors', 'state')
    op.drop_column('consignors', 'start_time')
    op.drop_column('consignors', 'note')
    op.drop_column('consignors', 'create_time')
    op.drop_column('consignors', 'company_size')
    op.drop_column('consignors', 'company_industry')
    op.drop_column('consignors', 'break_number')
    op.drop_column('consignors', 'address')
    # ### end Alembic commands ###
