"""empty message

Revision ID: b318b1237486
Revises: 17b1e1fcb235
Create Date: 2017-07-26 09:18:02.601099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b318b1237486'
down_revision = '17b1e1fcb235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_msgs', sa.Column('users', sa.Integer(), nullable=True))
    op.drop_constraint(u'user_msgs_ibfk_1', 'user_msgs', type_='foreignkey')
    op.create_foreign_key(None, 'user_msgs', 'users', ['users'], ['id'])
    op.drop_column('user_msgs', 'phone')
    op.drop_column('user_msgs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_msgs', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user_msgs', sa.Column('phone', mysql.VARCHAR(length=11), nullable=True))
    op.drop_constraint(None, 'user_msgs', type_='foreignkey')
    op.create_foreign_key(u'user_msgs_ibfk_1', 'user_msgs', 'users', ['user_id'], ['id'])
    op.drop_column('user_msgs', 'users')
    # ### end Alembic commands ###
