"""empty message

Revision ID: b785ac81f731
Revises: debc3bca199a
Create Date: 2017-07-19 15:41:30.576238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b785ac81f731'
down_revision = 'debc3bca199a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('car_length', sa.String(length=16), nullable=True))
    op.add_column('goods', sa.Column('car_type', sa.String(length=16), nullable=True))
    op.add_column('goods', sa.Column('end_qu', sa.String(length=255), nullable=True))
    op.add_column('goods', sa.Column('end_sheng', sa.String(length=255), nullable=True))
    op.add_column('goods', sa.Column('end_shi', sa.String(length=255), nullable=True))
    op.add_column('goods', sa.Column('start_qu', sa.String(length=255), nullable=True))
    op.add_column('goods', sa.Column('start_sheng', sa.String(length=255), nullable=True))
    op.add_column('goods', sa.Column('start_shi', sa.String(length=255), nullable=True))
    op.add_column('goods', sa.Column('start_zone', sa.String(length=10), nullable=True))
    op.add_column('goods', sa.Column('tiji', sa.String(length=16), nullable=True))
    op.add_column('goods', sa.Column('zhongliang', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'zhongliang')
    op.drop_column('goods', 'tiji')
    op.drop_column('goods', 'start_zone')
    op.drop_column('goods', 'start_shi')
    op.drop_column('goods', 'start_sheng')
    op.drop_column('goods', 'start_qu')
    op.drop_column('goods', 'end_shi')
    op.drop_column('goods', 'end_sheng')
    op.drop_column('goods', 'end_qu')
    op.drop_column('goods', 'car_type')
    op.drop_column('goods', 'car_length')
    # ### end Alembic commands ###
