"""empty message

Revision ID: ba61492e1c5b
Revises: 3d4cd63bf5a0
Create Date: 2017-08-01 08:36:41.167503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba61492e1c5b'
down_revision = '3d4cd63bf5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Driver_self_orders', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('goods_self_orders', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods_self_orders', 'price')
    op.drop_column('Driver_self_orders', 'price')
    # ### end Alembic commands ###
