"""empty message

Revision ID: bb4f6a300874
Revises: 684d336f9d79
Create Date: 2017-06-22 21:43:58.619007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4f6a300874'
down_revision = '684d336f9d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_msgs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_msgs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_msgs', type_='foreignkey')
    op.drop_column('user_msgs', 'user_id')
    # ### end Alembic commands ###
