"""empty message

Revision ID: bb9f94b57e99
Revises: b318b1237486
Create Date: 2017-07-27 08:26:35.126489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb9f94b57e99'
down_revision = 'b318b1237486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Driver_self_orders', sa.Column('state', sa.Integer(), nullable=True))
    op.drop_column('Driver_self_orders', 'static')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Driver_self_orders', sa.Column('static', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('Driver_self_orders', 'state')
    # ### end Alembic commands ###
