"""empty message

Revision ID: cfd1d743ef66
Revises: fcd624349dca
Create Date: 2017-07-10 11:03:43.507189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd1d743ef66'
down_revision = 'fcd624349dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_str', sa.String(length=20), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('run_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_tasks')
    # ### end Alembic commands ###
