"""empty message

Revision ID: d5f6893a8e55
Revises: 1896aacea1be
Create Date: 2017-09-25 13:23:14.592766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5f6893a8e55'
down_revision = '1896aacea1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_attribute_register')
    op.drop_table('follows')
    op.drop_constraint(u'articles_ibfk_1', 'articles', type_='foreignkey')
    op.drop_constraint(u'articles_ibfk_2', 'articles', type_='foreignkey')
    op.drop_column('articles', 'author_id')
    op.drop_column('articles', 'category_id')
    op.drop_constraint(u'category_top_ibfk_1', 'category_top', type_='foreignkey')
    op.drop_column('category_top', 'category_attribute_id')
    op.drop_constraint(u'categorys_ibfk_2', 'categorys', type_='foreignkey')
    op.drop_constraint(u'categorys_ibfk_1', 'categorys', type_='foreignkey')
    op.drop_column('categorys', 'category_attribute_id')
    op.drop_column('categorys', 'category_top_id')
    op.drop_constraint(u'comments_ibfk_2', 'comments', type_='foreignkey')
    op.drop_constraint(u'comments_ibfk_1', 'comments', type_='foreignkey')
    op.drop_column('comments', 'author_id')
    op.drop_column('comments', 'article_id')
    op.create_foreign_key(None, 'positions', 'users', ['users'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.add_column('comments', sa.Column('article_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'comments_ibfk_1', 'comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key(u'comments_ibfk_2', 'comments', 'articles', ['article_id'], ['id'])
    op.add_column('categorys', sa.Column('category_top_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('categorys', sa.Column('category_attribute_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'categorys_ibfk_1', 'categorys', 'category_attribute', ['category_attribute_id'], ['id'])
    op.create_foreign_key(u'categorys_ibfk_2', 'categorys', 'category_top', ['category_top_id'], ['id'])
    op.add_column('category_top', sa.Column('category_attribute_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'category_top_ibfk_1', 'category_top', 'category_attribute', ['category_attribute_id'], ['id'])
    op.add_column('articles', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'articles_ibfk_2', 'articles', 'users', ['author_id'], ['id'])
    op.create_foreign_key(u'articles_ibfk_1', 'articles', 'categorys', ['category_id'], ['id'])
    op.create_table('follows',
    sa.Column('follower_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('followed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], [u'users.id'], name=u'follows_ibfk_1'),
    sa.ForeignKeyConstraint(['follower_id'], [u'users.id'], name=u'follows_ibfk_2'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('category_attribute_register',
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('category_attribute_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_attribute_id'], [u'category_attribute.id'], name=u'category_attribute_register_ibfk_2'),
    sa.ForeignKeyConstraint(['category_id'], [u'categorys.id'], name=u'category_attribute_register_ibfk_1'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
