"""empty message

Revision ID: da6e39764401
Revises: b785ac81f731
Create Date: 2017-07-19 16:34:23.194997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6e39764401'
down_revision = 'b785ac81f731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('select_car_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'select_car_type')
    # ### end Alembic commands ###
