"""empty message

Revision ID: fbed1c9b0868
Revises: bb9f94b57e99
Create Date: 2017-07-28 21:04:44.007391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbed1c9b0868'
down_revision = 'bb9f94b57e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('car_type', sa.String(length=255), nullable=True))
    op.add_column('drivers', sa.Column('tiji', sa.String(length=255), nullable=True))
    op.add_column('drivers', sa.Column('zhongliang', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'zhongliang')
    op.drop_column('drivers', 'tiji')
    op.drop_column('drivers', 'car_type')
    # ### end Alembic commands ###
