"""empty message

Revision ID: fcd624349dca
Revises: bb4f6a300874
Create Date: 2017-06-26 16:20:19.390887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcd624349dca'
down_revision = 'bb4f6a300874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redis_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('redis_key', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('redis_key')
    )
    op.add_column(u'user_msgs', sa.Column('title', sa.String(length=64), nullable=True))
    op.drop_column(u'user_msgs', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user_msgs', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column(u'user_msgs', 'title')
    op.drop_table('redis_tasks')
    # ### end Alembic commands ###
