"""empty message

Revision ID: fd0d20578209
Revises: fbed1c9b0868
Create Date: 2017-07-29 10:41:10.838129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd0d20578209'
down_revision = 'fbed1c9b0868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_self_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_post', sa.Integer(), nullable=True),
    sa.Column('consignors', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consignors'], ['consignors.id'], ),
    sa.ForeignKeyConstraint(['driver_post'], ['driver_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods_self_orders')
    # ### end Alembic commands ###
